const Access = Object.freeze({
    // Project
    MEMBERS_AND_MANAGERS: 'MEMBERS_AND_MANAGERS',
    ALL_MANAGERS: 'ALL_MANAGERS',
    ONLY_MANAGER_OWNER: 'ONLY_MANAGER_OWNER',
    // Task and Tag
    ONLY_PROJECT_OWNER: 'ONLY_PROJECT_OWNER',
    // Task
    ASSIGNEE_AND_PROJECT_OWNER: 'ASSIGNEE_AND_PROJECT_OWNER',
    // Tag
    MEMBERS_AND_PROJECT_OWNER: 'ASSIGNEE_AND_PROJECT_OWNER',
});

module.exports = Access;